### ISSUE TITLE
vertaisarviointi 

### ISSUE THREAD

**Issue by stalola** [lxhelmer/dbcourseprogram#1]
- Sisäänkirjautuessa törmää ongelmaan: sisäänkirjautuminen ei onnistu, koska taulussa users ei ole saraketta username vaan name. Korjasin sarakkeen nimen tietokantaan ja nyt ei tule SQL-erroria, mutta tämänkään jälkeenkään rekisteröityminen ei onnistu. Lisäsin kuitenkin käyttäjän suoraan SQL-tauluun päästäkseni kokeilemaan sovellusta ja sisäänkirjautuminen toimi.
Näissä kohdissa olisi hyvä olla jokin error-koodi, jotta käyttäjä tietää, mistä virhetilanne johtuu.

- Sovelluksen käynnistäminen readme:n ohjeiden perusteella oli muuten sujuvaa, paitsi että schema.sql ilmeisesti on jäänyt päivittämättä users-taulun osalta.

- Koodin jakaminen tiedostoihin vaikuttaa loogiselta. Päällisin puolin koodi näyttää siistiltä, mutta jonkin verran on korjattavaa, jotta sovellus toimisi oikein.

**Comment by lxhelmer** [comment]
Tvittavat korjaukset tehty.
