### ISSUE TITLE
Vertaisarviointi

### ISSUE THREAD

**Issue by lsommarberg** [lxhelmer/dbcourseprogram#2]
Vertaisarviointi:

- En pääse avaamaan profiilisivua, sillä /profile reitissä on virhe muuttujan nimessä ('user_id' muuttuu 'uid')
- Ulkoasu on muuten selkeä. ‘To users’ - napin voisi piilottaa tavalliselta käyttäjältä kokonaan. 
- Esimerkiksi ainakin sql kyselyt voisi jakaa omiin tiedostoihin, samalla tyylillä kuin results.py on jo toteutettu
- Tietokanta näyttää sopivalta sovelluksen toimintoihin ja koodi on siistiä pieniä virheitä lukuunottamatta

**Comment by lxhelmer** [comment]
Korjaukset tehty.
